Running on cn9.hpc.itu.dk:
Running model {'results_folder': '../bank_results/HI-Large_all_bank/AML_HI-Large_all_bank', 'dataset': '../Data/all_bank_FraudGT/HI-Large/AML/HI-Large_Trans.csv', 'formatted': '../Data/all_bank_FraudGT/HI-Large/AML', 'title': 'all banks HI FraudGT', 'save_to': 'all_banks_HI_FraudGT', 'patterns':                Timestamp  From Bank  ... Is Laundering  Laundering Type
0       2022/08/09 05:14        952  ...             1            STACK
1       2022/08/13 13:09     111632  ...             1            STACK
2       2022/08/15 07:40     118693  ...             1            STACK
3       2022/08/15 14:19      13729  ...             1            STACK
4       2022/08/13 12:40      24750  ...             1            STACK
...                  ...        ...  ...           ...              ...
137931  2022/11/08 09:12       1538  ...             1          FAN-OUT
137932  2022/11/20 18:34       1538  ...             1          FAN-OUT
137933  2022/11/25 11:27       1538  ...             1          FAN-OUT
137934  2022/11/28 09:15       1538  ...             1          FAN-OUT
137935  2022/12/10 15:28       1538  ...             1          FAN-OUT

[137936 rows x 12 columns]}
/home/adgi/FraudGT/Analysis/analysis_all_bank.py:147: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  predictions_train = pd.read_csv(f'{results_folder}/predictions_train.csv',on_bad_lines='skip').drop_duplicates('Edge_ID')
/home/adgi/FraudGT/Analysis/analysis_all_bank.py:155: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  predictions_train = pd.read_csv(f'{results_folder}/predictions_train.csv',on_bad_lines='skip').drop_duplicates('Edge_ID')
Predictions size: (16103859, 4)
Full data size: (23169522, 11)
Difference: 7065663
/home/adgi/FraudGT/Analysis/analysis_all_bank.py:16: RuntimeWarning: invalid value encountered in cast
  true_labels = data['True_Label'].to_numpy().astype(int)
/home/adgi/FraudGT/Analysis/analysis_all_bank.py:17: RuntimeWarning: invalid value encountered in cast
  predicted_labels= data['predicted_binary'].to_numpy().astype(int)
Traceback (most recent call last):
  File "/home/adgi/FraudGT/Analysis/analysis_all_bank.py", line 180, in <module>
    confusion_matrix_plot(df_merged, title=model['title'], save_to=f'{model['save_to']}')
  File "/home/adgi/FraudGT/Analysis/analysis_all_bank.py", line 40, in confusion_matrix_plot
    precision = precision_score(true_labels, predicted_labels, average='binary')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/sklearn/metrics/_classification.py", line 2247, in precision_score
    p, _, _, _ = precision_recall_fscore_support(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 189, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/sklearn/metrics/_classification.py", line 1830, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adgi/.conda/envs/fraudGT/lib/python3.12/site-packages/sklearn/metrics/_classification.py", line 1613, in _check_set_wise_labels
    raise ValueError(
ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].
